### PR TITLE
Remove injection in CassandraMetricsIT (fixes #96)

### LINKED ISSUE #96: Fix CassandraMetricsNativeIT
In our builds, `CassandraMetricsNativeIT` is reported successful but with zero tests:

```
[INFO] Running com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 s - in com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
```

However in quarkus-platform, this test fails:

```
[INFO] Running com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.013 s <<< FAILURE! - in com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT
[ERROR] com.datastax.oss.quarkus.tests.CassandraMetricsNativeIT  Time elapsed: 0.013 s  <<< ERROR!
org.junit.platform.commons.JUnitException: @Inject is not supported in NativeImageTest tests. Offending field is com.datastax.oss.quarkus.tests.CassandraMetricsIT.cqlSession
```

It seems that we should not inject beans in native tests. A small refactoring of `CassandraMetricsIT` should bring everything back to normal: remove `cqlSession` field and trigger a query to the database inside the REST resource, not in the test class itself.

### PR DESCRIPTION
**Pull request by absurdfarce**

### CODE REVIEW

File: integration-tests/src/test/java/com/datastax/oss/quarkus/tests/CassandraMetricsIT.java [hunk 1]
```diff
@@ -18,24 +18,23 @@
...
-  @Inject QuarkusCqlSession cqlSession;
-
   @Test
   public void should_report_driver_metrics_via_metrics_endpoint() {
-    // when
-    cqlSession.execute("select *  from system.local");
+
+    /* Trigger some CQL activity via the test REST endpoint.  We're not particularly
+     * interested in the product that gets created here, only that it was created. */
+    when().post("/cassandra/product/test1").then().statusCode(Response.Status.OK.getStatusCode());
```
Comment (adutra) [inline integration-tests/src/test/java/com/datastax/oss/quarkus/tests/CassandraMetricsIT.java:37]: Nit: can we change the product id to `metrics-test` or something similar? When running many ITs in a row it's easy to have side-effects when creating items with similar ids.

Comment (absurdfarce) [reply integration-tests/src/test/java/com/datastax/oss/quarkus/tests/CassandraMetricsIT.java:37]: Good idea, I like this... fix coming up
